apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage-claim
  namespace: cloudchamp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
