apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cloudchamp
  labels:
    app: api
spec:
  selector:
    role: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31510     
  type: NodePort
