apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloudchamp
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: cloudacademydevops/frontend:v11
          imagePullPolicy: Always
          env:
            - name: REACT_APP_APIHOSTPORT
              value: "http://api:31510"  
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ok
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
