apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage-claim
  namespace: cloudchamp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
