apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
  namespace: cloudchamp
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongo-0  # Ensure this path exists on the node

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
  namespace: cloudchamp
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongo-1  # Ensure this path exists on the node

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
  namespace: cloudchamp
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongo-2  # Ensure this path exists on the node
